import "../assets/globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const arabic = localFont({
    src: "../assets/fonts/me_quran_volt_newmet.ttf",
    subsets: ["arabic"],
    variable: "--font-arabic",
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" dir="ltr" className="scroll-smooth">
            <body
                className={`${inter.variable} ${arabic.variable} font-sans bg-no-repeat bg-gray-100`}
            >
                {children}
            </body>
        </html>
    );
}
